FROM golang:1.12-alpine3.11 AS builder

RUN apk add git

WORKDIR /src
COPY . .
RUN go get
RUN go build .

FROM alpine:3.11 AS runner

COPY --from=builder /src/uploader /usr/local/bin/uploader
CMD [ "/usr/local/bin/uploader" ]