FROM golang:1.15-alpine3.13 AS builder

RUN apk add git

WORKDIR /src
COPY . .
RUN go get && \
    go build .

FROM alpine:3.13 AS runner

COPY --from=builder /src/api /usr/local/bin/api
CMD [ "/usr/local/bin/api" ]
